import {
    NavigationState,
    TabState,
    SubPageEntry,
    SubPageType,
    GlobalOverlayType,
} from "components/nav_state.slint";
import { ChatListView, ConversationRow } from "chats/chat_list.slint";
import { ContactListView } from "contacts/contacts.slint";
import { DiscoverView } from "discovery/discover.slint";
import { MeView } from "me/me.slint";
import { BottomNavBar } from "components/bottom_nav.slint";
import { LeftNavBar } from "components/left_nav.slint";
import { SubPageView } from "./subpage.slint";
import { AuthView } from "components/auth.slint";
import { Horizontal } from "../material-1.0/ui/components/horizontal.slint";
import { AppState } from "components/app_state.slint";
export { AppState }from "components/app_state.slint";
import { ScanView } from "global/scan.slint";
import { ImageViewer } from "global/image.slint";
import { AudioView } from "global/audio.slint";
import { VideoView } from "global/video.slint";
import { ScreenShareView } from "global/screen.slint";

export component MainWindow inherits Window {

    in property <bool> logged-in: false;
    in property <bool> auth-busy: false;
    in property <string> auth-message: "";

    in property <bool> is-mobile: true;

    callback login(string, string);
    callback register(string, string);
    callback logout();

    callback pop-sub-page(int);
    callback push-sub-page(int, SubPageType, int);

    function select_tab(i: int) {
        AppState.nav-state.active-tab = i;
    }

    preferred-height: root.is-mobile ? 844px : 768px;
    preferred-width: root.is-mobile ? 390px : 1024px;

    if !root.logged-in:
    AuthView {
        message: root.auth-message;
        busy: root.auth-busy;
        uid <=> AppState.user-id;
        login(uid, pass) => { root.login(uid, pass); }
        register(uid, pass) => { root.register(uid, pass); }
    }

    if root.logged-in && root.is-mobile:
    Rectangle {
        width: 100%;
        height: 100%;

        if AppState.nav-state.active-tab >= 0:
        VerticalLayout {
            width: 100%;
            height: 100%;
            spacing: 0px;

            Rectangle {
                width: 100%;
                background: #ffffff;
                clip: true;

                ChatListView {
                    visible: AppState.nav-state.active-tab == 0;
                    width: 100%;
                    height: 100%;
                    navigate-to(t, p) => { AppState.push-sub(t, p); }
                }
                ContactListView {
                    visible: AppState.nav-state.active-tab == 1;
                    width: 100%;
                    height: 100%;
                    navigate-to(t, p) => { AppState.push-sub(t, p); }
                }
                DiscoverView {
                    visible: AppState.nav-state.active-tab == 2;
                    width: 100%;
                    height: 100%;
                    navigate-to(t, p) => { AppState.push-sub(t, p); }
                }
                MeView {
                    visible: AppState.nav-state.active-tab == 3;
                    width: 100%;
                    height: 100%;
                    navigate-to(t, p) => { AppState.push-sub(t, p); }
                }
            }

            BottomNavBar {
                active-tab: AppState.nav-state.active-tab;
                tab-clicked(i) => { root.select_tab(i); }
            }
        }
        for entry[i] in AppState.nav-state.tabs[AppState.nav-state.active-tab].sub-history:
        SubPageView {
            width: 100%;
            height: 100%;
            visible: i == AppState.nav-state.tabs[AppState.nav-state.active-tab].sub-top;
            page: entry.page;
            payload: entry.payload;
            go-back() => { AppState.pop-sub(); }
            navigate-to(t, p) => { AppState.push-sub(t, p); }
        }
    }

    if root.logged-in && !root.is-mobile:
    HorizontalLayout {
        width: 100%;
        height: 100%;
        spacing: 0px;
        LeftNavBar {
            width: 58px;
            height: 100%;
            active-tab: AppState.nav-state.active-tab;
            tab-clicked(i) => { root.select_tab(i); }
        }

        Rectangle {
            width: 280px;
            background: #e4e1e1;
            clip: true;

            ChatListView {
                visible: AppState.nav-state.active-tab == 0;
                width: 100%;
                height: 100%;
            }
            ContactListView {
                visible: AppState.nav-state.active-tab == 1;
                width: 100%;
                height: 100%;
            }
            DiscoverView {
                visible: AppState.nav-state.active-tab == 2;
                width: 100%;
                height: 100%;
            }
            MeView {
                visible: AppState.nav-state.active-tab == 3;
                width: 100%;
                height: 100%;
            }
        }

        for entry[i] in AppState.nav-state.tabs[AppState.nav-state.active-tab].sub-history:
        SubPageView {
            width: 100%;
            height: 100%;
            visible: i == AppState.nav-state.tabs[AppState.nav-state.active-tab].sub-top;
            page: entry.page;
            payload: entry.payload;
            go-back() => { AppState.pop-sub(); }
            navigate-to(t, p) => { AppState.push-sub(t, p); }
        }
    }

    if AppState.nav-state.global-overlay == GlobalOverlayType.ImageViewer: ImageViewer { }
    if AppState.nav-state.global-overlay == GlobalOverlayType.QrScanner: ScanView { }
    if AppState.nav-state.global-overlay == GlobalOverlayType.VideoCall: VideoView { }
    if AppState.nav-state.global-overlay == GlobalOverlayType.AudioCall: AudioView { }
    if AppState.nav-state.global-overlay == GlobalOverlayType.ScreenShare: ScreenShareView { }
}
