import { SubPageType } from "components/nav_state.slint";
import { ChatView } from "chats/chat.slint";
import { ChatSettingView } from "chats/chat_setting.slint";
import { ContactProfileView } from "contacts/profile.slint";
import { SettingView } from "me/setting.slint";
import { GroupProfileView } from "contacts/group_profile.slint";
import { AddContactView } from "contacts/add_contact.slint";
import { AddGroupView } from "contacts/add_group.slint";
import { DiscoverDetailView } from "discovery/discover_detail.slint";
import { PomegranateSeedView } from "discovery/pomegranate_seed.slint";

export component SubPageView inherits Rectangle {
    in property <SubPageType> page;
    in property <int> payload;

    callback go-back();
    callback navigate-to(SubPageType, int);

    if root.page == SubPageType.ChatRoom: ChatView {
        chat-id: root.payload;
        on-back => { root.go-back(); }
        open-setting => { root.navigate-to(SubPageType.ChatSetting, root.payload); }
    }
    if root.page == SubPageType.ChatSetting: ChatSettingView {
        chat-id: root.payload;
        on-back => { root.go-back(); }
    }
    if root.page == SubPageType.ContactProfile: ContactProfileView {
        user-id: root.payload;
        on-back => { root.go-back(); }
    }
    if root.page == SubPageType.GroupProfile: GroupProfileView {
        group-id: root.payload;
        on-back => { root.go-back(); }
    }
    if root.page == SubPageType.SettingsMain: SettingView {
        on-back => { root.go-back(); }
        open-sub(page) => { root.navigate-to(page, 0); }
    }
    if root.page == SubPageType.SettingsGeneral: SettingView {
        on-back => { root.go-back(); }
    }
    if root.page == SubPageType.AddContact: AddContactView {
        on-back => { root.go-back(); }
    }
    if root.page == SubPageType.AddGroup: AddGroupView {
        on-back => { root.go-back(); }
    }
    if root.page == SubPageType.DiscoverDetail: DiscoverDetailView {
        on-back => { root.go-back(); }
    }
    if root.page == SubPageType.PomegranateSeed: PomegranateSeedView {
        on-back => { root.go-back(); }
    }
}
