[package]
name = "camera"
version = "0.1.0"
edition = "2024"

[dependencies]

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-foundation = { version = "0.3.2" }
objc2-core-foundation = { version = "0.3.2" }
objc2-core-video = { version = "0.3.2" }
objc2-core-media = { version = "0.3.2" }
objc2-av-foundation = { version = "0.3.2" }
dispatch2 = { version = "0.3", features = ["objc2"] }
