import { ScrollView, VerticalBox } from "std-widgets.slint";
import { SubPageType } from "../components/nav_state.slint";
import { Icon, Glyph, Variant } from "../components/icon.slint";
import { SettingItem, ProfileItem } from "../components/item.slint";
import { Theme } from "../theme.slint";
import { AppState } from "../components/app_state.slint";


export component MeView inherits Rectangle {
    background: #f5f5f5;
    in-out property <int> selected-key: -1;

    callback navigate-to(SubPageType, int);
    ProfileItem {
        name: AppState.user-id;
        nickname: AppState.nickname;
        peer-id: AppState.peer-id;
        show-qr => { AppState.show-qr-code(); }
    }

    ScrollView {
        width: 100%;
        height: parent.height - 100px;
        y: 100px;
        VerticalLayout {
            width: 100%;
            spacing: 0px;

            SettingItem {
                width: 100%;
                id: 1;
                icon: Glyph.notes;
                title: "我的笔记";
                selected: root.selected-key == 1;
                clicked => { root.selected-key = 1; root.navigate-to(SubPageType.MyNote, 0); }
            }

            SettingItem {
                width: 100%;
                id: 2;
                icon: Glyph.collection;
                title: "我的收藏";
                selected: root.selected-key == 2;
                clicked => { root.selected-key = 2; root.navigate-to(SubPageType.MyCollect, 0); }
            }

            SettingItem {
                width: 100%;
                id: 3;
                icon: Glyph.share;
                title: "我的分享";
                selected: root.selected-key == 3;
                clicked => { root.selected-key = 3; root.navigate-to(SubPageType.MyShare, 0); }
            }

            SettingItem {
                width: 100%;
                id: 4;
                icon: Glyph.setting;
                title: "设置";
                selected: root.selected-key == 4;
                clicked => { root.selected-key = 4; root.navigate-to(SubPageType.Settings, 0); }
            }
        }
    }
}
