import { ScrollView, VerticalBox } from "std-widgets.slint";
import { SubPageType } from "../components/nav_state.slint";
import { Icon, Glyph } from "../components/icon.slint";
import { SettingItem } from "../components/item.slint";
import { Theme } from "../theme.slint";


export component MeView inherits Rectangle {
    background: #f5f5f5;

    callback navigate-to(SubPageType, int);

    ScrollView {
        width: 100%;
        height: 100%;

        VerticalLayout {
            width: 100%;
            spacing: 0px;
            padding-left: 8px;
            SettingItem {
                width: 100%;
                id: 1;
                icon: Glyph.collection;
                title: "收藏";
                clicked => { root.navigate-to(SubPageType.SettingsGeneral, 0); }
            }

            SettingItem {
                width: 100%;
                id: 2;
                icon: Glyph.setting;
                title: "设置";
                clicked => { root.navigate-to(SubPageType.SettingsMain, 0); }
            }
        }
    }
}
