import { Icon, Glyph } from "../components/icon.slint";
import { Theme } from "../theme.slint";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { SubPageType, AppState } from "../components/app_state.slint";
import { Header } from "../components/header.slint";

export component MyNoteView inherits Rectangle {
    width: 100%;
    height: 100%;
    background: #f5f5f5;

    Header {
        name: "My Note";
    }
}
