import { SubPageType } from "../components/nav_state.slint";
import { Horizontal } from "../../material-1.0/material.slint";
import { Header } from "../components/header.slint";

export component SettingView inherits Rectangle {
    width: 100%;
    height: 100%;
    background: #f5f5f5;
    callback on-back();
    callback open-sub(SubPageType);

    Header {
        name: "setting";
        on-back => { root.on-back() }
    }
}
