import { AppState } from "../components/app_state.slint";
import { GlobalOverlayType } from "../components/nav_state.slint";
import { Icon, Glyph } from "../components/icon.slint";

export component ErrorView inherits Rectangle {
    width: 100%;
    height: 100%;
    background: #00000055;
    clip: true;

    // 点空白处也关闭
    TouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            AppState.nav-state.global-overlay = GlobalOverlayType.None;
            AppState.error-message = "";
        }
    }

    Rectangle {
        x: (parent.width - 160px) / 2;
        y: (parent.height - 160px) / 2;
        width: 160px;
        height: 160px;
        border-radius: 12px;
        background: #000000B3;

        Icon {
            x: (parent.width - 28px) / 2;
            y: 20px;
            glyph: Glyph.close-circle;
            size: 28px;
            tint: #c44e4e;
        }

        Text {
            x: 20px;
            y: 80px;
            width: parent.width - 40px;
            height: 72px;
            text: AppState.error-message;
            font-size: 14px;
            color: #ffffffcc;
            wrap: word-wrap;
        }
    }
}
