import { AppState } from "../components/app_state.slint";
import { GlobalOverlayType } from "../components/nav_state.slint";
export component VideoView inherits Rectangle {
    in property <bool> isMuted;
    in property <bool> isSpeakerOn;
    width: 100%;
    height: 100%;
    background: #00000088;
    TouchArea {
        width: 100%;
        height: 100%;
        clicked => { AppState.nav-state.global-overlay = GlobalOverlayType.None; }
    }
}
