import { SubPageType } from "../components/nav_state.slint";
import { ContactRow } from "../components/app_state.slint";
import { ContactListItem } from "../components/item.slint";
import { Theme } from "../theme.slint";

export component ContactListView inherits Rectangle {
    in property <[ContactRow]> rows: [];
    in-out property <int> selected-key: -1;

    width: 100%;
    height: 100%;
    background: Theme.bg;
    callback navigate-to(SubPageType, int);

    out property <length> row-h: 48px;
    out property <length> viewport-h: root.rows.length * root.row-h;

    if root.rows.length == 0:
    Text {
        y: 180px;
        width: parent.width;
        text: "暂无联系人，添加后会出现在这里";
        color: #9aa0b4;
        font-size: 14px;
        horizontal-alignment: center;
        wrap: word-wrap;
    }

    Flickable {
        x: 0px;
        y: 0px;
        width: parent.width;
        height: parent.height;
        viewport-height: root.viewport-h;
        interactive: true;

        for row[i] in root.rows: ContactListItem {
            x: 0px;
            y: root.row-h * i;
            width: parent.width;
            height: root.row-h;
            id: row.id;
            peer_id: row.peer_id;
            title: row.name;
            selected: row.id == root.selected-key;

            clicked => { root.selected-key = row.id; root.navigate-to(SubPageType.ContactProfile, row.id); }
        }
    }
}
