import { Icon, Glyph } from "../components/icon.slint";
import { Theme } from "../theme.slint";
import { AppState } from "../components/app_state.slint";
import { Header } from "../components/header.slint";
export component ContactProfileView inherits Rectangle {
    in property <int> user-id;
    callback on-back();

    Header {
        name: "profile";
        on-back => { root.on-back() }
    }
}
