export enum PageType {
    Chat,
    Contact,
    Discover,
    Me,
}

export enum SubPageType {
    ChatRoom,
    ChatSetting,
    AddGroup,
    GroupProfile,
    ContactProfile,
    AddContact,
    DiscoverDetail,
    DiscoverMiniProgram,
    SettingsMain,
    SettingsGeneral,
    SettingsPrivacy,
    LanguagePicker,
}

export enum GlobalOverlayType {
    None,
    ImageViewer,
    QrScanner,
    AudioCall,
    VideoCall,
    ScreenShare,
}

export struct SubPageEntry {
    page: SubPageType,
    payload: int,
}

export struct TabState {
    sub-history: [SubPageEntry],
}

export struct NavigationState {
    active-tab: int,
    tabs: [TabState],
    global-overlay: GlobalOverlayType,
}
