import { CardView } from "../components/card.slint";
import { Theme } from "../theme.slint";
import { DiscoverCard } from "../components/app_state.slint";
import { SubPageType, AppState } from "../components/app_state.slint";
import { SearchBar } from "../components/search.slint";

export component DiscoverView inherits Rectangle {
    in property <[DiscoverCard]> cards: [];
    callback like-toggled(int);

    width: 100%;
    height: 100%;
    background: Theme.bg;

    out property <length> gap: 8px;
    out property <int> n-cols:  2;
    out property <length> col-w: (root.width - (root.n-cols + 1) * root.gap) / root.n-cols;
    out property <length> card-h: root.col-w * 4 / 3 + 90px;
    out property <int> n-rows: (root.cards.length > 0)
        ? floor((root.cards.length + root.n-cols - 1) / root.n-cols)
        : 0;
    out property <length> viewport-h: (root.n-rows > 0)
        ? root.gap + root.n-rows * (root.card-h + root.gap)
        : 0px;

    SearchBar {
        y: 0px;
    }

    if root.cards.length == 0:
    Text {
        y: 180px;
        text: "暂无内容";
        horizontal-alignment: center;
        font-size: 14px;
        color: Theme.fg-muted;
    }

    Flickable {
        x: 0px;
        y: 48px;
        width: parent.width;
        height: parent.height - 48px - (AppState.is-mobile ? 58px : 0px);
        content-height: root.viewport-h;
        interactive: true;

        for card[i] in root.cards: CardView {
            x: root.gap + (root.col-w + root.gap) * Math.mod(i, root.n-cols);
            y: root.gap + (root.card-h + root.gap) * floor(i / root.n-cols);
            width: root.col-w;
            title: card.title;
            user: card.user;
            is-liked: card.liked;
            likes: card.likes;
            id: card.id;
            clicked(id) => { AppState.push-sub(SubPageType.DiscoverDetail, id); }
            like-toggled => { root.like-toggled(card.id); }
        }
    }
}
